### ISSUE TITLE
Forced Fossil Modifiers Ignore Other Fossils

### ISSUE THREAD

**Issue by NickRyder** [Sectoidfodder/PoETheoryCraft#2]
Fossils should respect all the weighting modifiers - regardless of whether or not they are forced.

One can check this by using, for example, by using Glyphic Fossil and any fossil which blocks tags on one of the corrupted essence mods.

**Comment by Sectoidfodder** [comment]
This one's tricky because essence mods don't have base weights to be modified.

Making a note to test this in-game.  If fossil weights somehow apply to essence mods, Glyphic + Corroded + Prismatic should block three out of the four corrupted mods on rings, giving "10% reduced reflected damage taken" every time.

[edit] Better yet, Corroded blocks 3/4 mods on boots and Prismatic blocks the last one.  What happens then?
